version = 0.1
[default.deploy.parameters]
stack_name = "marcos-translator"
resolve_s3 = true
s3_prefix = "marcos-translator"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "account1"
